DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING  NOT NULL,
    description CHARACTER VARYING  NOT NULL,
    price NUMERIC NOT NULL,
    new BOOLEAN NOT NULL,
    sale BOOLEAN NOT NULL,
    stock INTEGER NOT NULL,
    category CHARACTER VARYING UNIQUE NOT NULL,
    imagepath CHARACTER VARYING UNIQUE NOT NULL

);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    email CHARACTER VARYING UNIQUE NOT NULL,
    password CHARACTER VARYING NOT NULL,
    name CHARACTER VARYING NOT NULL,
    role CHARACTER VARYING NOT NULL,
    sale BOOLEAN NOT NULL,
    PRIMARY KEY(email)
    FOREIGN KEY(email) REFERENCES carts(email)

);

DROP TABLE IF EXISTS carts CASCADE;
CREATE TABLE IF NOT EXISTS carts (
    cartid INTEGER NOT NULL,
    email CHARACTER VARYING UNIQUE NOT NULL,
    sold BOOLEAN NOT NULL,
    date_added TIMESTAMP,

    PRIMARY KEY(cartid)
    FOREIGN KEY(cartid) REFERENCES incarts(cartid)

);

DROP TABLE IF EXISTS incarts CASCADE;
CREATE TABLE IF NOT EXISTS incarts (
    cartid INTEGER UNIQUE NOT NULL,
    id INTEGER UNIQUE NOT NULL,
    quantity INTEGER,
    date_added TIMESTAMP,

    PRIMARY KEY(cartid,id)
    FOREIGN KEY(cartid) REFERENCES incarts(cartid)

);